### ISSUE TITLE
Doku Detailfragen

### ISSUE THREAD

**Issue by manuel-91** [Jonas-commits/Neo-Keyboard-Adapter#3]
Hey Jonas,

vielen Dank für das Repo und die ausführliche Dokumentation. Da hast du echt viel Mühe reingesteckt. Ich habe die Hardware erfolgreich aufgebaut (danke für die Bilder mit Markierungen!). Dabei kamen mir ein paar Fragen auf:
1. Was hat es mit dem '[fix](https://github.com/Jonas-commits/Neo-Keyboard-Adapter/blob/master/hardware/fix.jpg)' auf sich?
2. Was mache ich mit der [boards.txt](https://github.com/Jonas-commits/Neo-Keyboard-Adapter/blob/master/hardware/boards.txt)? Ich habe sie nicht gebraucht. Ist die für AVR-dude?
3. Bei mir geht das Uploaden nur wenn ich vorher den Reset auf GND hole und glück beim Timing habe (das Board hat ja leider keinen Reset Button). Ist das nur bei mir so? Falls nicht, würde ich gerne noch eine Zeile in der README.md ergänzen evtl mit Verweis auf [die Fehlermeldung](https://stackoverflow.com/questions/49283074/arduino-leonardo-avrdude-butterfly-recv-programmer-is-not-responding).

...ich bin mal so frei und schreibe die Anfrage auf deutsch, da vermutlich alle Neo User Deutsch sprechen...

Diesen Text habe ich mit deiner Firmware in Neo geschrieben! :-D, Grüße!

**Comment by Jonas-commits** [comment]
Hallo:
1. Das Bild zeigt, wo das VBus Wire durchzuschneiden ist und durch einen 5V Anschluss zu ersetzen ist.
2. Ich habe zunächst die board.txt bearbeitet um den 3.3V Arduino Micro zu programmieren, bis ich dann entdeckt habe, dass man auch das Lillypad auswählen kann.
3. ich vermute du hast genau das gemacht, was ich auch zuerst gemacht habe und den Arduino Micro ausgewählt und hast damit den falschen Bootloader auf dem Device (Siehe https://github.com/Jonas-commits/Neo-Keyboard-Adapter#arduino-pro-micro)

**Comment by manuel-91** [comment]
1. Ahhh! Ok, jetzt check ichs, das schwarze Kabel ist das orange skizzierte. Ich hatte das Kabel direkt geführt ohne Stiftleiste. Aber den RAW Pin vom Host board habe ich nicht verbunden, funktioniert aber komischerweise trotzdem. Der ist auf 0V... wenn ich es richtig verstanden verbindet das schwarze Kabel + Stift die drei orangenen Kreise:

![image](https://user-images.githubusercontent.com/45081089/106382640-34c38980-63c1-11eb-8757-ff46a58515cb.png)

Werde ich nachfädeln.

2. Ah, danke für den Hintergrund.
3. Da bin ich mir eigentlich ziemlich sicher, dass ich das nicht gemacht habe... _"Soft-Brick"_ ohne zu wissen wie an das wieder los wird fand ich ziemlich abschreckend:-P Aber wenn es der falsche Bootloader ist erklärt das, warum die IDE keinen Reset auslösen kann... kriege ich das mit Arduino IDE -> Werkzeuge -> Bootloader brennen wieder hin? Oder bin ich jetzt darauf verdammt bei jedem Flashen den Reset zu drücken? o.O

**Comment by Jonas-commits** [comment]
ja, das orangene Kabel ist das schwarze. Ich hatte zunächst das Shield oben drauf gesetzt und 1:1 gepinnt und mich gewundert warum es nicht geht und dann nachgeflickt. das Host Shield braucht die 5V nur an VBus. Es ist nicht erforderlich, die eingemalte Linie nachzuziehen, der Pin ist auf dem Shield nicht verbunden.

Wenn du kein 5V Update machst und es original lässt, kommen halt nur 3V an deiner Tastatur an. Kann reichen, kann auch nicht reichen, nach USB Standard sollte es halt 5V sein, und spätestens wenn du eine beleuchtete Tastatur hast, reicht es nicht mehr.

Der richtige Bootloader wird jedes mal korrigiert beim flashen (deswegen bekommst du überhaupt den falschen drauf), also wenn du das richtige Device auswählst sollte es korrigiert sein.

Ich habe 10 Dinger aus 3 verschiedenen Batches zusammengebaut und kann die Probleme nicht nachvollziehen.

**Comment by manuel-91** [comment]
Okay, jetzt funktionierts mit dem Reset per IDE. Vermutlich hatte ich zwischendrin doch die falsche Arduino Version ausgewählt.
