### ISSUE TITLE
Ebene4: wortweises Springen per Strg funktioniert nicht

### ISSUE THREAD

**Issue by manuel-91** [Jonas-commits/Neo-Keyboard-Adapter#4]
Ich nutze sehr gerne die Pfeiltasten der 4. Ebene. Diese für sich funktionieren sehr gut, jedoch funktioniert Strg dazu wie erwartet:

(Tastenbezeichnung im Quertz-Sprech)

Ohne Strg:
* AltGr + F = Pfeil rechts :heavy_check_mark: 
* AltGr + Umschalt + F = Markieren rechts :heavy_check_mark: 

Strg:
* Strg + Echte Pfeiltaste = zum nächsten Wort springen :heavy_check_mark: 
* AltGr + Strg + F = zum nächsten Wort springen :no_entry: stattdessen bewegt sich der Cursor nur nach rechts
* AltGr + F (gedrückt halten) + Strg = zum nächsten Wort springen :heavy_check_mark: 

Strg + Umschalt:
* Strg + Umschalt + Echte Pfeiltaste = markiere nächstes Wort :heavy_check_mark: 
* AltGr + Umschalt + Strg + F= Markiere nächstes Wort :no_entry: stattdessen wird nur das nächste Zeichen markiert
* AltGr + Umschalt + F + Strg = Markiere nächstes Wort :heavy_check_mark:

Pfeil rechts ist hier stellvertredend, für Pfeil links, Pos1/Ende gilt das selbe.

Leider ist der "workaround" zuerst die Pfeiltaste zu erzeugen und dann Strg dazu zu drücken nicht praktikabel, da man dafür die Zeichenwiederholung des Betriebbsystems braucht. Ich habe es hier nur zum Fehler eingrenzen notiert.

Getestet auf Windows und Arch Linux.

**Comment by Jonas-commits** [comment]
Klingt plausibel. Nach momentaner Implementierung werden alle Modifier verworfen außerhalb Ebene 1 und 2. Ich werde schauen, was man gegen tun kann

**Comment by Jonas-commits** [comment]
Hatte diesen Use-Case nicht bedacht beim Design. Sollte jetzt klappen

**Comment by manuel-91** [comment]
Yay! Vielen Dank Jonas für die schnelle Erweiterung, läuft! Ich hatte schon befürchtet, dass das Feature nur durch umfangreicheres Code umgraben ergänzt werden kann, aber du hast ja eine sehr elegante Lösung gefunden :+1:
