### ISSUE TITLE
Possible use for external keyboards on iPad

### ISSUE THREAD

**Issue by mlichtblau** [Jonas-commits/Neo-Keyboard-Adapter#6]
I stumbled upon this project, while I was looking for a way to use the Neo layout on an external keyboard on my iPad.
Do you think this would work out of the box, or otherwise be possible to implement?
I would be happy to contribute, if you think this is feasible at all.
Thank you!

**Comment by Jonas-commits** [comment]
Haven't tried this yet. Just tried on my android phone, it works. 
How do you plug in keyboards in an iPad though? If you are able to connect a standard USB keyboard to the iPad, i am confident also this adapter works, as it emulates the HID Boot standard, which is the most basic standard and almost every device understands it.

**Comment by mlichtblau** [comment]
Yes, just via USB-C. I will give it a try, thanks for your quick response!
