### ISSUE TITLE
Adjustments for alternative Neo Layouts  (Bone / Mine / Noted)

### ISSUE THREAD

**Issue by jankrahl** [Jonas-commits/Neo-Keyboard-Adapter#8]
Hello and thank you for this project.
I have my parts arriving soon and want to build this for use with Neo Mine.

Do I need to adjust any other files other than [NeoReportParser.cpp](https://github.com/Jonas-commits/Neo-Keyboard-Adapter/blob/master/src/keyboard/NeoReportParser.cpp)?

If all goes well I will of couse make a pull request for the additional layout.

**Comment by jankrahl** [comment]
I have finished most of the work.

Only some keys in layer 5 & 6 do not work, but I am not motivated to fix them for now, as I am not using these layers at all.

Layers 1-4 fully work with the Unicode Helper script and good enough without.

I am still refining some openscad code I wrote for a 3D printed case and will create a pull request afterwards.

**Comment by Jonas-commits** [comment]
Hello, 
Yes, you'd only need to edit that file for the layout to work in general. For the compose sequences to work with the adapted layout, you'd need to also change the mapping in the map in the compose generator (https://github.com/Jonas-commits/Neo-Keyboard-Adapter/blob/master/src/compose_generator/generate.py) and regenerate the compose map.

3D Case my brother generated a great one already, I will ask him to commit the files for that :)
